lambdaclass/cairo_native

.github/workflows/rustdoc.yml

instead of the library docs for now

add book ci

---

sierra2mlir/src/statements/mod.rs

Reduces boilerplate when getting the value, hiding whether its from a block argument or a operation result.

streamline variable storage

---

sierra2mlir/src/compiler.rs
sierra2mlir/src/libfuncs/mod.rs

Fix felt addition and subtraction modulo.

---

.github/workflows/ci.yml

make clippy deny warnings on ci

make clippy deny warnings on ci

---

.github/workflows/ci.yml
Makefile
examples/boolean.cairo
examples/boolean.ll
examples/boolean.mlir
examples/boolean.sierra
examples/simple_enum.cairo
examples/simple_enum.ll
examples/simple_enum.mlir
examples/simple_enum.sierra
sierra2mlir/src/compiler.rs
sierra2mlir/src/libfuncs/sierra_enum.rs
sierra2mlir/src/types/mod.rs
sierra2mlir/src/userfuncs/mod.rs
sierra2mlir/src/utility.rs
sierra2mlir/tests/comparison.rs
sierra2mlir/tests/comparison/enum_return.sierra
sierra2mlir/tests/example_compiles.rs

adds enum print support, fixes issues with the gep that i was using wrongly before
this also adds the prints for u8,u16,u32,u64,u128
not sure about u128 working though

add enum print, fix enum bug

---

sierra2mlir/Cargo.toml

since they yanked the version working bad

fix smol_str

---

sierra2mlir/Cargo.toml
sierra2mlir/src/compiler.rs
sierra2mlir/src/lib.rs

update melior, load all dialects

---

sierra2mlir/benches/programs/fib-optimized.mlir
sierra2mlir/benches/programs/fib.mlir

update bench fib mlir

---

examples/boolean.cairo
examples/boolean.mlir
examples/boolean.sierra
examples/felt_is_zero.mlir
examples/fib.mlir
examples/print_test.mlir
examples/simple-optimized.mlir
examples/simple.mlir
examples/simple_enum.mlir
sierra2mlir/src/compiler.rs
sierra2mlir/src/libfuncs/mod.rs

implements the following:
bool_and_impl
bool_not_impl
bool_xor_impl
bool_or_impl
related: #18

bool libfuncs

---

examples/boolean.cairo
examples/boolean.ll
examples/boolean.mlir
examples/boolean.sierra
examples/felt_is_zero.ll
examples/fib.ll
examples/print_test.ll
examples/simple-optimized.ll
examples/simple.ll
examples/simple_enum.ll
sierra2mlir/src/libfuncs/mod.rs

implements bool_to_felt252
closes #18

implement bool_to_felt252

---

sierra2mlir/Cargo.toml
sierra2mlir/benches/cairo.rs
sierra2mlir/benches/programs/fib0.json

Add `cairo-vm` benchmark.

---

.github/workflows/ci.yml
cli/Cargo.toml
sierra2mlir/Cargo.toml
sierra2mlir/tests/comparison.rs

updates to the current latest cairo commit, this is needed due to indexing not being implemented in the latest tagged release

update sierra commit

---

sierra2mlir/Cargo.toml
sierra2mlir/src/compiler.rs
sierra2mlir/src/libfuncs/mod.rs
sierra2mlir/src/statements/inline_jumps.rs
sierra2mlir/src/utility.rs

updates melior and uses the functions it provides where possible

minor cleanup and update melior

---

.github/workflows/ci.yml

Since we're back on the most recent cairo tag again, re-enables the cairo release check

Re-enables cairo release check

---

docs/src/SUMMARY.md
docs/src/intro.md
docs/src/layout.md
docs/src/setup.md

improve docs

---

cli/Cargo.toml
scripts/fetch-corelibs.sh
sierra2mlir/Cargo.toml

Updates all deps to cairo v1.0.0

update to cairo v1.0.0

---

sierra2mlir/src/compiler/helpers/array.rs
sierra2mlir/src/libfuncs/mod.rs
sierra2mlir/src/statements/inline_jumps.rs
sierra2mlir/src/statements/mod.rs
sierra2mlir/tests/comparison.rs
sierra2mlir/tests/comparison/array/slice.cairo

implement array_slice libfunc

---

.github/scripts/merge-benches.sh
.github/workflows/bench-hyperfine.yml
scripts/bench-hyperfine.sh
scripts/find-llvm.sh

Add benchmarking script with `hyperfine`.

---

Cargo.toml
src/bin/sierra2mlir.rs
src/bin/sierrajit.rs
src/compiler.rs
src/debug_info.rs
src/debug_info/statements.rs
src/ffi.cpp
src/ffi.rs
src/jit_runner.rs
src/lib.rs
src/libfuncs/enum.rs
src/libfuncs/uint8.rs
src/types/enum.rs
src/utils.rs
src/values/array.rs

We'll need testing, sooner or later.

Add unit testing infrastructure.

---

.gitignore
programs/benches/fib.c
programs/benches/fib.cairo
programs/benches/fib_1k.c
programs/benches/fib_1k.cairo
programs/benches/map.c
programs/benches/map.cairo
scripts/bench-hyperfine.sh
src/debug_info/statements.rs
src/libfuncs/enum.rs

- Add long(-ish) running benchmarking using hyperfine.
- Fix previous enum fix (operand does not dominate error).
- Fix debug info bug.

Add benchmarking and fix stuff.

---

programs/array_get.cairo
src/debug_info.rs
src/libfuncs.rs
src/libfuncs/array.rs
src/libfuncs/box.rs
src/types.rs
src/types/box.rs

- box type
- unbox libfunc
- array get libfunc
- array tests

libfuncs progress

---

README.md
rustfmt.toml
src/bin/sierrajit.rs

Add `rustfmt.toml`.

---

src/libfuncs/array.rs

- snapshot pop front
- snapshot pop back

more array libfuncs

---

programs/erc20.cairo
src/libfuncs/uint16.rs
src/libfuncs/uint32.rs
src/libfuncs/uint64.rs
src/libfuncs/uint8.rs

adds some uint libfuncs needed for erc20

uint progress, add erc20 program

---

src/libfuncs/uint16.rs
src/libfuncs/uint32.rs
src/libfuncs/uint64.rs
src/libfuncs/uint8.rs

Added tests for the remaining unsigned integer libfuncs. Fixed the bugs detected while at it.

Add remaining uint tests and fix bugs.

---

Cargo.toml
programs/pedersen_ex.cairo
runtime/Cargo.toml
runtime/src/lib.rs
src/bin/sierrajit.rs
src/libfuncs.rs
src/libfuncs/felt252.rs
src/libfuncs/pedersen.rs
src/metadata/runtime_bindings.rs
src/types.rs
src/types/pedersen.rs
src/utils.rs
src/values.rs
src/values/pedersen.rs
tests/common.rs
tests/programs.rs

Implements the pedersen builtin type and the hash libfunc.

Pedersen libfunc

---

Cargo.toml
src/starknet.rs

syscall wrappers

---

README.md

Adds a list of  library functions to the README.md.
The list should be updated each time a library function is implemented.

Add list of library functions to the README.md

---

README.md
src/libfuncs.rs
src/libfuncs/bitwise.rs
src/libfuncs/felt252.rs

This libfunc was in the pre-refactor. It has now been ported.

Add `bitwise` libfunc.

---

.github/scripts/merge-benches.sh
.github/workflows/bench-hyperfine.yml

fix bench ci spam

---

README.md
src/libfuncs/bool.rs

libfunc bool_to_felt252

---

README.md
src/libfuncs/uint128.rs
src/libfuncs/uint16.rs
src/libfuncs/uint32.rs
src/libfuncs/uint64.rs
src/libfuncs/uint8.rs
src/utils.rs

Add integer square root libfuncs.

---

README.md
src/lib.rs
src/types/felt252_dict.rs

updates the list to make it clearer whats done and what needs to be done, also mention the need to fetch the cairo corelibs

update readme list and instructions

---

runtime/src/lib.rs
src/compiler.rs
src/jit_runner.rs
src/lib.rs
src/libfuncs/enum.rs
src/types/felt252.rs
src/values.rs

Add more documentation.

---

.github/workflows/bench-hyperfine.yml
Cargo.lock
Cargo.toml
Dockerfile
runtime/Cargo.toml
scripts/fetch-corelibs.sh

update to cairo 2.1.0

---

examples/erc20.rs
examples/starknet.rs
src/easy.rs

so the erc20 example is simpler

extend easy api

---

examples/erc20.rs
examples/starknet.rs
src/metadata/syscall_handler.rs
src/starknet.rs

Some more changes for integration with SiR, mainly making some StarknetSyscallHandler trait self references mutable and removing a Debug trait bound.

More changes for SiR integration

---

src/execution_result.rs
src/lib.rs
src/utils.rs

Add `NativeExecutionResult` struct and serialization/deserialization functionality

feat: add `NativeExecutionResult` struct

---

.github/workflows/bench-hyperfine.yml
.github/workflows/ci.yml
.github/workflows/rustdoc.yml
Cargo.lock
Cargo.toml
Makefile
README.md
build.rs
scripts/bench-hyperfine.sh
src/bin/cairo-native-run.rs
src/context.rs
src/libfuncs/array.rs
src/libfuncs/uint128.rs
src/libfuncs/uint16.rs
src/libfuncs/uint256.rs
src/libfuncs/uint32.rs
src/libfuncs/uint64.rs
src/libfuncs/uint8.rs
src/utils.rs
src/values/felt252_dict.rs
tests/cases.rs
tests/common.rs

update to llvm 17

---

Makefile
README.md

Just added the new libfuncs and removed a stale makefile target.

Added new libfuncs

---

.github/workflows/bench-hyperfine.yml
.github/workflows/ci.yml
examples/erc20.rs
examples/starknet.rs
programs/benches/factorial.c
programs/benches/factorial_100.c
programs/benches/fib.c
programs/benches/fib_1k.c
programs/benches/map.c
src/error/jit_engine.rs
src/executor.rs
src/jit_runner.rs
src/libfuncs/gas.rs
src/libfuncs/stark_net.rs
src/metadata/gas.rs
src/module.rs
src/starknet.rs
src/types.rs
src/types/gas_builtin.rs
src/values/gas_builtin.rs
tests/common.rs
tests/starknet/keccak.rs

Make gas type be u128

---

examples/erc20.rs
examples/starknet.rs
src/starknet.rs
tests/starknet/keccak.rs

This one slipped past by and should be mut too.

syscallhandler keccak self mut

---

src/libfuncs/stark_net.rs

Implement `class_hash_to_felt252`.

---

DEVELOPER-GUIDE.md
README.md
examples/easy_api.rs
examples/erc20.rs
examples/starknet.rs
src/cache.rs
src/compiler.rs
src/error/jit_engine.rs
src/jit_runner.rs
src/lib.rs
src/libfuncs/array.rs
src/libfuncs/bool.rs
src/libfuncs/snapshot_take.rs
src/types/enum.rs
src/types/nullable.rs
tests/boolean.rs

Fix spelling issues.

---

Cargo.toml
examples/erc20.rs
examples/starknet.rs
src/executor.rs
src/lib.rs
src/metadata.rs
src/metadata/debug_utils.rs
src/metadata/syscall_handler.rs
src/module.rs
src/starknet.rs
src/utils.rs
tests/common.rs
tests/starknet/keccak.rs

Just some utilities to help debug MLIR-generated code.

Add MLIR debug utils meta.

---

Cargo.lock
Cargo.toml
Makefile
runtime/Cargo.toml
scripts/check-corelib-version.sh

pin cairo dependencies and corelib checks

---

src/libfuncs.rs
src/libfuncs/uint512.rs

Implement u512 libfuncs.

---

.github/workflows/ci.yml
Dockerfile

The dockerfile got outdated, this makes it up to date.
Also adds a CI check.

Update outdated dockerfile and add to CI

---

Cargo.lock
Cargo.toml
benches/compile_time.rs
benches/libfuncs.rs
benches/util.rs
programs/compile_benches/dijkstra.cairo
programs/compile_benches/extended_euclidean_algorithm.cairo
programs/compile_benches/fast_power.cairo
programs/compile_benches/sha256.cairo
src/context.rs

Adds compilation time criterion benchmarks.
Fixes #283
Local results:
<details>
Hardware:
```
OS: Gentoo 2.14 x86_64
Kernel: 6.1.67-gentoo
CPU: AMD Ryzen 7 5800X (16) @ 4.85 GHz
Memory: 31.28 GiB
```
```
Compilation With Independent Context/fast_power.cairo/1
time:   [12.647 ms 12.828 ms 13.023 ms]
Compilation With Independent Context/extended_euclidean_algorithm.cairo/1
time:   [7.0165 ms 7.1112 ms 7.2271 ms]
Compilation With Independent Context/dijkstra.cairo/1
time:   [17.040 ms 17.176 ms 17.352 ms]
Compilation With Independent Context/sha256.cairo/1
time:   [56.372 ms 56.838 ms 57.396 ms]
Compilation With Shared Context/fast_power.cairo/1
time:   [9.8847 ms 9.9151 ms 9.9504 ms]
Compilation With Shared Context/extended_euclidean_algorithm.cairo/1
time:   [4.6608 ms 4.6780 ms 4.6967 ms] …
```

Compilation time benches

---

runtime/src/lib.rs
src/error/libfuncs.rs
src/error/types.rs
src/libfuncs/drop.rs
src/metadata/realloc_bindings.rs
src/metadata/runtime_bindings.rs
src/types.rs
src/utils.rs
src/values.rs

Done:
- Arrays
- Dicts
- Box
- Nullable
fixes #281

Free Allocations

---

tests/cases.rs
tests/cases/uint/safe_divmod.cairo

Updates the test file and unlocks the corresponding test case

Update test/cases/uint/safe_divmod.cairo file

---

src/cache.rs
src/compiler.rs
src/error/libfuncs.rs
src/jit_runner.rs
src/libfuncs.rs
src/libfuncs/bool.rs
src/libfuncs/cast.rs
src/libfuncs/ec.rs
src/libfuncs/enum.rs
src/libfuncs/felt252.rs
src/libfuncs/gas.rs
src/libfuncs/sint128.rs
src/libfuncs/sint16.rs
src/libfuncs/sint32.rs
src/libfuncs/sint64.rs
src/libfuncs/sint8.rs
src/libfuncs/uint128.rs
src/libfuncs/uint16.rs
src/libfuncs/uint256.rs
src/libfuncs/uint32.rs
src/libfuncs/uint64.rs
src/libfuncs/uint8.rs
src/types/snapshot.rs

Removes some unwraps and converts others to expects when we are really sure it won't panic.
Fixes #262

Remove unwraps

---

README.md
src/bin/cairo-native-run.rs
src/jit_runner.rs
src/libfuncs.rs
src/libfuncs/bytes31.rs
src/libfuncs/gas.rs
src/libfuncs/stark_net.rs
src/types.rs
src/types/bytes31.rs
src/values.rs

document todos and implement bytes31

---

Cargo.lock
Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

upd starknet types core to 0.5.0 and also update it on the runtime crate

---

.gitignore
Makefile
runtime/README.md

add readme for runtime and a make target

---

src/libfuncs/box.rs
src/libfuncs/nullable.rs
src/types/nullable.rs

Fix nullable snapshots and a memory leak.

---

examples/erc20.rs
examples/starknet.rs
src/libfuncs/stark_net.rs
src/starknet.rs
src/utils.rs
tests/starknet/keccak.rs

Fixes https://github.com/lambdaclass/cairo_native/issues/100

Implement get_execution_info_v2

---

Cargo.lock
Cargo.toml
src/executor.rs
src/starknet.rs
src/values.rs

Needed to add the sandbox in SiR

add serde feature

---

src/execution_result.rs
src/executor.rs
src/executor/aot.rs
src/executor/jit.rs
src/metadata/gas.rs
src/values.rs

Adds some missing derives, specially Debug.
Add serde on some structures i forgot on the previous PR

Make library more user friendly

---

Cargo.lock
Cargo.toml
Makefile
README.md
benches/util.rs
examples/erc20.rs
examples/starknet.rs
runtime/Cargo.toml
src/bin/cairo-native-compile.rs
src/bin/cairo-native-dump.rs
src/libfuncs.rs
src/libfuncs/array.rs
src/libfuncs/box.rs
src/libfuncs/cast.rs
src/libfuncs/enum.rs
src/libfuncs/felt252_dict.rs
src/libfuncs/gas.rs
src/libfuncs/nullable.rs
src/metadata/gas.rs
src/types.rs
src/values.rs
tests/alexandria.rs
tests/cases/array/append.cairo
tests/common.rs
tests/starknet/contracts/test_keccak.cairo
tests/starknet/keccak.rs

Update Cairo dependencies to `2.5.0`.

---

Cargo.lock
Cargo.toml
Makefile
README.md
env-macos.sh
runtime/Cargo.toml
src/debug_info/statements.rs
src/libfuncs.rs
src/libfuncs/array.rs
src/libfuncs/cast.rs
src/libfuncs/uint128.rs
src/libfuncs/uint256.rs
tests/cases/uint/downcasts.cairo
tests/starknet/keccak.rs

update to 2.5.3

---

src/libfuncs/box.rs

The `box` and `unbox` libfuncs weren't working properly with stack-allocated enums (those with more than a single variant that are not C-style enums).

Fix `box` and `unbox` with enums.

---

tests/common.rs
tests/tests/cases.rs
tests/tests/uint.rs

The comparison test framework had a bug where it failed to compare the VM vs native results in some cases. This PR rewrites that part making it both easier to read and understand, and fixing the bug in the process.

Fix enum payload bug.

---

cairo-tests/src/integer_test.cairo
src/libfuncs/sint128.rs
src/libfuncs/sint16.rs
src/libfuncs/sint32.rs
src/libfuncs/sint64.rs
src/libfuncs/sint8.rs

It wasnt checking properly on the from_felt252 libfunc for sints
Related to #473

Fix some signed int bugs/tests

---

cairo-tests/src/integer_test.cairo

enable missed working test in cairo-tests

---

src/utils.rs

This PR addresses the following issue: https://github.com/lambdaclass/cairo_native/issues/483

Increase test coverage of Utils module

---

src/libfuncs/array.rs

- [#480 ] Linked to Github Issue

adding more tests

---

src/arch/aarch64.s
src/arch/x86_64.s
src/executor.rs

Rename aot trampoline and fix compatibility issues.

---

src/debug_info/statements.rs
src/executor.rs

Small refactoring

---

src/libfuncs.rs

Add unit tests for `libfuncs` `switch` function in order to test various configurations.
Resolves #484.

Add unit tests for `libfuncs` `switch` function.

---

.github/workflows/ci.yml

make format comment not be added if it was always ok

---

cairo-tests/src/fmt_test.cairo
src/executor.rs
src/types/box.rs

Fix segfault when a snapshot of a box is taken

---

src/execution_result.rs
tests/tests/mod.rs
tests/tests/result.rs

test: from execution result

---

src/values.rs

Increase coverage of the JIT values

---

src/block_ext.rs
src/libfuncs/cast.rs

Chore: refactor cast

---

src/libfuncs/gas.rs

Refactored gas libfuncs to use BlockExt

Refactor gas

---

src/libfuncs/bytes31.rs

Update bytes31 use blockext

---

src/libfuncs/ec.rs

Refactored ec to use BlockExt.

Refactor ec ops

---

tests/tests/programs.rs

Adds a test for a self referencing structure with a recursive function.

add self referencing test

---

Cargo.lock
src/values.rs

increase `to_jit` test coverage for `Enum`

---

Cargo.lock
src/module.rs

increase test coverage of `NativeModule`

---

Cargo.lock
cairo-tests/src/print_test.cairo

enable print tests in cairo-test

---

Cargo.lock
Cargo.toml
src/debug_info.rs

Adds a unit test for DebugLocations. Adds rstest to avoid boilerplate code. Solves #486.

test: debug info module

---

Cargo.lock
src/execution_result.rs
src/executor.rs
src/ffi.rs
src/lib.rs

Add more docs about cairo native within the code

---

tests/cases/brainfuck.cairo
tests/tests/cases.rs

add brainfuck interpreter test case

---

src/libfuncs/debug.rs

Refactored debug libfuncs to use the BlockExt trait

---

src/libfuncs/nullable.rs

Refactored nullable libfuncs to use the BlockExt trait

---

src/libfuncs/ec.rs

Refactored ec libfuncs to use the BlockExt trait

---

src/types/nullable.rs

Refactored nullable types to use the BlockExt trait

---

src/types/box.rs

Refactored box types to use the BlockExt trait

---

src/libfuncs/uint64.rs

Refactored u64 to use the BlockExt trait

---

src/block_ext.rs

Refactor BlockExt trait methods

---

src/libfuncs.rs

Refactored libfuncs to use the BlockExt trait

---

src/types.rs

Refactored types to use the BlockExt trait

---

src/libfuncs/uint8.rs

Refactored u8 to use the BlockExt trait

---

Cargo.lock
Cargo.toml

Update `melior` dependency.

---

.github/codecov.yml
.github/workflows/bench-hyperfine.yml
.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/rustdoc.yml
README.md
rust-toolchain.toml

update rust to 1.79.0

---

docs/gas.md
src/libfuncs/sint8.rs

docs: gas accounting

---

src/libfuncs/felt252.rs

add unit tests for `felt252_div` in libfuncs

---

docs/builtins-counter.md

Adds documentation about the builtins counters.

docs: builtins counters

---

src/bin/cairo-native-stress/main.rs

Improves documentation on the Stress Test Binary

Improve stress test documentation

---

src/types/nullable.rs

Fix Nullable<T> snapshot segfault

---

README.md

add aot remarks to readme and update libfunc list

---

src/bin/cairo-native-stress/main.rs
src/cache/aot.rs
src/cache/jit.rs
src/executor.rs
src/executor/aot.rs
src/executor/jit.rs

Required to fix the blockifier contract cache.

Make the contract caches thread-compatible.

---

runtime/src/lib.rs
src/libfuncs/felt252_dict_entry.rs
src/metadata/runtime_bindings.rs
src/types/felt252_dict.rs
src/utils.rs
src/values.rs

Also frees the allocated dict values, beforehand they werent and probs leaked.
Fixes #723

Fix dict snapshot

---

Cargo.lock
Cargo.toml
examples/erc20.rs
examples/starknet.rs
src/bin/cairo-native-run.rs
src/libfuncs/starknet.rs
src/starknet.rs
src/starknet_stub.rs
src/types.rs
src/types/starknet.rs
tests/tests/starknet/programs/syscalls.cairo
tests/tests/starknet/secp256.rs
tests/tests/starknet/syscalls.rs

sha256 syscalls

---

.github/workflows/bench-hyperfine.yml
.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/rustdoc.yml
rust-toolchain.toml
src/compiler.rs

update to rust 1.80.0

---

src/arch.rs
src/arch/aarch64.rs
src/arch/x86_64.rs
src/executor.rs

Add error handling to JitValueWithInfoWrapper::to_bytes

---

src/arch/aarch64.rs

Add unit tests for `AbiArgument` for integers

---

.github/workflows/bench-hyperfine.yml
.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/rustdoc.yml
rust-toolchain.toml

update to rust 1.80.1

---

.github/workflows/ci.yml

Parallelize coverage workflow

---

Cargo.lock
Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs
src/libfuncs/ec.rs
src/libfuncs/pedersen.rs
src/libfuncs/poseidon.rs
src/metadata/runtime_bindings.rs
src/utils.rs

Update EC related code and deps [2.7.0]

---

src/bin/scarb-native-test.rs
src/ffi.cpp

update scarb native test

---

Cargo.toml

Remove unused dependencies from Cargo.toml

---

Cargo.lock
Cargo.toml
src/bin/cairo-native-run.rs

fix cairo-native-run

---

Cargo.lock
Cargo.toml
runtime/Cargo.toml

Updates the version and changes the git deps to versioned

Prepare for release

---

Cargo.lock
Cargo.toml
runtime/Cargo.toml

The next release, to include the latest fixes.

Version v0.2.0-alpha.2

---

.github/workflows/bench-hyperfine.yml

This PR fixes the issue with the constant comment creation instead of just updating it.

Fix Ci comment repetition 

---

docs/implementing_libfuncs.md
src/arch.rs
src/executor.rs

update implementing libfuncs doc

---

src/libfuncs/circuit.rs

move 2 circuit allocas to init block

---

src/executor.rs

Remove panic from executor.rs

---

src/error.rs
src/ffi.rs

Remove panic in ffi.rs

---

src/types.rs
src/types/enum.rs
src/types/felt252_dict.rs
src/types/snapshot.rs
src/types/struct.rs

Remove panics in types

---

src/libfuncs/enum.rs
src/types.rs
src/utils.rs
src/values.rs

Remove missing panics

---

.github/workflows/release.yml

fix github ci release 

---

src/libfuncs/array.rs

Fix empty array slicing.

---

.github/workflows/daily.yml

fix daily ci

---

README.md
docs/mlir.md

add workshop to docs

---

Cargo.lock
Cargo.toml
runtime/Cargo.toml

bump native version to v0.2.6

---

.github/workflows/daily.yml

Increase concurrency level in daily blocks

---

.github/ISSUE_TEMPLATE/daily_failure.md
.github/workflows/daily.yml

Upload daily comparison results as an artifact

---

tests/tests/circuit.rs
tests/tests/mod.rs

Add circuit gas compare test

---

.github/workflows/release.yml

Missed this little detail where archive needs to be set

fix github release

---

Cargo.lock
Cargo.toml

bump version to 0.3.1

---

src/values.rs

Remove panic in src/values.rs

---

Cargo.lock
Cargo.toml
README.md

Prepares for new release: 0.3.3

Bump version to 0.3.3

---

Cargo.lock
Cargo.toml
README.md

Prepare for release v0.3.4

---

.github/workflows/release.yml

Try to fix release ci binary generation again

---

src/libfuncs/gas.rs
src/metadata/gas.rs
src/metadata/runtime_bindings.rs
src/runtime.rs
src/types/gas_builtin.rs
src/utils.rs

This PR adds gas documentation, and removes some duplicated logic that appears in some gas related libfuncs.
Closes #1158
This PR also updates some gas builtin mentions, that actually refer to costs builtin (outdated references)

Improve gas documentation (and mini refactor)

---

src/error.rs
src/libfuncs/circuit.rs
src/libfuncs/starknet.rs
src/values.rs

This PR cherrypicks:
- https://github.com/lambdaclass/cairo_native/pull/1171
- https://github.com/lambdaclass/cairo_native/pull/1175
Onto v0.4.1.

v0.4.1: cherrypick bug fixes

---

Cargo.lock
Cargo.toml
src/bin/cairo-native-run.rs
src/bin/utils/test.rs
src/context.rs
src/executor/contract.rs
src/metadata/gas.rs

Cherrypick of #1183 to make a bugfix release

v0.4.1: Reuse cairo-lang GasMetadata calculations #1183

---

Cargo.toml
README.md

Bumps Cairo Native version to 0.4.2

v0.4.2: Prepare for release

---

Makefile
debug_utils/sierra-emu/Cargo.toml

Enable sierra-emu checks

---

Cargo.lock
Cargo.toml
README.md

Prepare for Release: v0.5.0-rc.5

Prepare for Release: v0.5.0-rc.5

---

debug_utils/sierra-emu/src/vm/gas.rs

This PR implements `get_available_gas` the last gas related libfunc missing.

[Sierra-Emu] implement `get_available_gas` libfunc

---

Cargo.lock
Cargo.toml
README.md

Prepare for v0.3.5

---

Cargo.lock
Cargo.toml
README.md

Prepare for v0.3.6

---

src/libfuncs/circuit.rs
src/types/circuit.rs

Use dynamic arrays instead of static arrays for circuit data #1237

---

Cargo.lock
Cargo.toml
README.md

Prepare for 0.5.0-rc.6

---

src/libfuncs/bytes31.rs
src/libfuncs/int.rs
src/libfuncs/int_range.rs
src/libfuncs/pedersen.rs
src/libfuncs/poseidon.rs
src/libfuncs/starknet.rs
src/libfuncs/uint256.rs
src/libfuncs/uint512.rs

Adds documentation for the following PRs:
- https://github.com/lambdaclass/cairo_native/pull/1299
- https://github.com/lambdaclass/cairo_native/pull/1291
- https://github.com/lambdaclass/cairo_native/pull/1284
- https://github.com/lambdaclass/cairo_native/pull/1283
- https://github.com/lambdaclass/cairo_native/pull/1282
- https://github.com/lambdaclass/cairo_native/pull/1281
- https://github.com/lambdaclass/cairo_native/pull/1280
- https://github.com/lambdaclass/cairo_native/pull/1279
- https://github.com/lambdaclass/cairo_native/pull/1277
- https://github.com/lambdaclass/cairo_native/pull/1276
- https://github.com/lambdaclass/cairo_native/pull/1274
- https://github.com/lambdaclass/cairo_native/pull/1273

Improve builtin counting documentation on already merged fixes

---

Cargo.lock
Cargo.toml
README.md

This release mainly includes the builtin counting feature.

Prepare for release 0.6.0-rc.1

---

Cargo.lock
Cargo.toml
README.md
src/bin/cairo-native-compile.rs

Prepare for release 0.6.0

---

LICENSE-MIT
README.md

Add dual license
Previously only apache 2.0
Now also MIT

Add dual license MIT APACHE

---

LICENSE-MIT
README.md
docs/debugging.md
src/bin/cairo-native-compile.rs
src/libfuncs.rs
tests/tests/circuit.rs

Merges the next branch with latest main.

[Next] Sync with main
