- cli/Cargo.toml
- sierra2mlir/benches/execution.rs
- sierra2mlir/src/compiler.rs
- sierra2mlir/src/lib.rs
The benchmark stopped working due to a change in the `op_func_call` method, we should add it to the CI I guess.
> fix the fib benchmark, add some transform passes

- .gitignore
- examples/print_test.ll
- examples/print_test.mlir
- sierra2mlir/Cargo.toml
- sierra2mlir/src/compiler.rs
- sierra2mlir/src/lib.rs
- sierra2mlir/src/libfuncs/mod.rs
- sierra2mlir/src/statements/mod.rs
- sierra2mlir/src/types/mod.rs
- sierra2mlir/src/utility.rs
- sierra2mlir/tests/comparison.rs
- sierra2mlir/tests/comparison/.gitignore
- sierra2mlir/tests/comparison/id.sierra
- sierra2mlir/tests/comparison/simple_return.sierra
- sierra2mlir/tests/comparison/tuple_return.sierra
This adds the initial framework for tests that run sierra both via mlir and via starkware's cairo runner and compare the results. Could be changed to use the ExecutionEngine, but at that point I think it's worth making a PR to have the cli's run function get the result from the execution engine and return it and use that which imo should be a separate PR. The wrappers generated here would also be useful for that as they could be repurposed to return a vector/array/tensor of felts rather than printing it
> Cairo runner tests

- sierra2mlir/src/compiler.rs
- sierra2mlir/src/libfuncs/mod.rs
- sierra2mlir/src/statements/mod.rs
- sierra2mlir/src/types/mod.rs
- sierra2mlir/src/utility.rs
- sierra2mlir/tests/comparison.rs
Always stores the types as SierraTypes, holding all the information instead of just the Type, and losing info such as field types in structs.
This will allow us to implement some things better in the future, such as enums i think, it also feels nicer.
I also removed repeated code for the add,sub,mul
> clean type storage

- cli/Cargo.toml
- sierra2mlir/Cargo.toml
- sierra2mlir/tests/comparison.rs
Since cairo is moving at a fast pace, it's better to pin the revision so local lock files are what we expect, otherwise ci might run a newer commit. Giving unexpected results
> pin cairo commit, fix tests due to cairo update

- Makefile
- cli/src/main.rs
The input now doesn't need an explicit -i flag.
> make cli easier to use

- examples/uint.cairo
- examples/uint.sierra
- sierra2mlir/src/libfuncs/mod.rs
- sierra2mlir/tests/example_compiles.rs
Implementation of the following libfuncs:
- `u8_to_felt252`
- `u16_to_felt252`
- `u32_to_felt252`
- `u64_to_felt252`
- `u128_to_felt252`
> Implement `u???_to_felt252` libfuncs.

- .github/workflows/ci.yml
also uses https://github.com/dtolnay/rust-toolchain
instead of the outdated (2021) action-rs actions
> update ci checkout to version 3 to avoid ci warnings

- .github/workflows/ci.yml
- cli/Cargo.toml
- cli/src/main.rs
- sierra2mlir/benches/execution.rs
- sierra2mlir/src/compiler.rs
- sierra2mlir/src/lib.rs
- sierra2mlir/src/statements/mod.rs
- sierra2mlir/src/userfuncs/mod.rs
- sierra2mlir/tests/comparison.rs
- sierra2mlir/tests/example_compiles.rs
Allow loading Cairo files directly, without having to convert them to Sierra first.
> Make cairo sources loadable.

- sierra2mlir/benches/execution.rs
- sierra2mlir/src/lib.rs
the bench stopped working due to a change in the function naming.
also i reorder the transform passes to be after the conversions due to it triggering a llvm assertion (they show if you compile llvm with assertions on, which aid development)
> fix bench and a assertion due to transform order

- sierra2mlir/src/statements/inline_jumps.rs
- sierra2mlir/src/statements/mod.rs
- sierra2mlir/tests/comparison.rs
Adds to the comparison tests to run the compilation multiple times and check the output is identical. Also runs the tests with and without the optimisation flag set and makes sure the behaviour is the same
> Determinism tests

- sierra2mlir/Cargo.toml
- sierra2mlir/src/lib.rs
Linking the MLIR C utils library (for the JIT engine) currently works only on linux due to the library extension (`.so`). This PR fixes that issue and makes it so that it'll work in the three main OSes.
> Make MLIR C utils library work on linux, macos and windows.

- sierra2mlir/benches/execution.rs
requires having .sierra files under examples to run all benches (e.g with `make compile-mlir`)
This adds compile time benchmarks using all the examples we have under examples/
> add benchmarks for compiling

- .github/workflows/ci.yml
- Cargo.toml
- Makefile
- sierra2mlir/benches/cairo.rs
- sierra2mlir/benches/execution.rs
- sierra2mlir/src/compiler/external_funcs.rs
- sierra2mlir/tests/comparison.rs
- sierra2mlir/tests/comparison/out/.gitignore
Changes the tests so they don't depend on lli, which has problems piping the output, rather using the execution engine from mlir with the passed file descriptor.
As far as i tested, this fixes the tests failing sometimes.
> don't rely on lli for tests, use file descriptor, improving stability

- Makefile
- README.md
- scripts/comparison.sh
- Remove `cairo-run` env var.
- Use `.cairo` for benchmarking instead of `.sierra` (due to the sierra parser bug).
- Run `make build` before benchmarking to update the binaries.
> Fix benchmarking

- .github/scripts/check-git-deps.sh
- cli/Cargo.toml
- scripts/fetch-corelibs.sh
- sierra2mlir/Cargo.toml
- Update `cairo-lang-compiler` in the CLI to 1.1.0.
- Update `cairo-lang-sierra` in the CLI to 1.1.0.
- Update `cairo-lang-compiler` in the compiler to 1.1.0.
- Update `cairo-lang-sierra` in the compiler to 1.1.0.
- Update `cairo-lang-sierra-gas` in the compiler to 1.1.0.
- Update `cairo-lang-to-casm` in the compiler to 1.1.0.
- Update `cairo-lang-ap-change` in the compiler to 1.1.0.
- Update `cairo-lang-utils` in the compiler to 1.1.0.
- Update `cairo-lang-runner` in the compiler to 1.1.0.
> Update `cairo-lang-*` dependencies version to `1.1.0`.

- scripts/bench-hyperfine.sh
The MLIR bench failed due to not loading libraries at runtime
> fix hyperfine bench script

- src/compiler.rs
- src/libfuncs.rs
- src/libfuncs/enum.rs
Currently, tail recursion avoids calling the function and therefore the frame that would reside on the stack. However, there are some operations, such as `llvm.alloca` that allocate space on the stack. The compiler is not smart enough to understand when those go out of scope and reuse the space and instead allocates more space, which defeats the whole purpose of tail recursive functions.
This PR fixes this by adding making a block accessible to the libfunc builders which is guaranteed to be executed only once for tail recursive functions. All `llvm.alloca` instructions have been moved there.
> Fix tail recursion.

- src/libfuncs/enum.rs
- src/types/enum.rs
A cairo enum like the one below will generate the following MLIR layouts for each variant:
```cairo
enum MyEnum {
A: u8,
B: u64,
}
```
| Variant | Align | Size | Aligned payload offset |
| ------- | ----- | ---- | ---------------------- |
| `MyEnum::A` | 1 | 1 | 1 |
| `MyEnum::B` | 8 | 8 | 8 |
This is as expected. Now, to force MLIR to respect alignments, the `enum` will use the variant with the largest align as its default payload; that is, `MyEnum::B`. This leaves the following layout (including padding):
| Offset | Type | Description |
| ------ | ---- | ----------- |
| 0 | `u8` | Enum discriminant. |
| 1 | `[u8; 7]` | Padding. |
| 8 | `u64` | Payload. |
For reference, `MyEnum::A` would have the following layout:
| Offset | Type | Description |
| ------ | ---- | ----------- |
| 0 | `u8` …
> Fix `enum` type.

- src/jit_runner.rs
- src/libfuncs/uint8.rs
- src/types/enum.rs
- src/values.rs
- src/values/array.rs
- src/values/enum.rs
- src/values/felt252.rs
- src/values/gas_builtin.rs
- src/values/range_check.rs
- src/values/struct.rs
- src/values/uint16.rs
- src/values/uint32.rs
- src/values/uint64.rs
- src/values/uint8.rs
- Implement missing de/serialization for the `array` type.
- Implement missing de/serialization for the `enum` type.
- Implement missing de/serialization for the `arrays` type.
- Fix de/serialization of `felt252` and `uintN` types (avoid `serde_json` dependency).
> Implement de/serialization for values.

- src/lib.rs
- src/libfuncs/enum.rs
- src/types/enum.rs
- src/values/enum.rs
Enums are failing on Mac OS due to the way LLVM handles padding. Our solution is to make all paddings explicit and mark the intermediate structs as packed. This way, LLVM will not generate padding, but the fields will still be properly aligned.
> Attempt to fix the enums.

- programs/benches/factorial.c
- programs/benches/factorial_100.c
- programs/benches/fib.c
- programs/benches/fib_1k.c
- programs/benches/map.c
Some configurations seemed to remove the actual benchmark code since it wasn't directly called. This PR fixes this, although requires a C compiler that supports `__attribute__(())`.
> Fix native benchmark wrappers.

- .github/workflows/ci.yml
- README.md
- scripts/bench-hyperfine.sh
The benchmarking script that runs hyperfine uses the cairo-run command to run programs through the cairo-vm, and defaults to running whatever cairo-run command is present in $PATH.
An environment variable allowing specifying a location for the command was added to the script and its use documented in the README.md
> Added env var for cairo-run command in hyperfine script

- examples/easy_api.rs
- programs/examples/hello.cairo
- runtime/src/lib.rs
- src/easy.rs
- src/lib.rs
Add an easy to use API to compile and execute a program using the JIT. It is intended for rapid prototyping, and not to be used as is in general.
> Add easy API and an example on how to use it.

- src/libfuncs/enum.rs
- src/types/enum.rs
- src/utils.rs
- tests/programs.rs
Enums were represented as packed structs with manual filling because without filling they would not move the data of the non-default variants. By making them packed they lost their alignment making the de/serialization fail in some cases when within structs.
This PR fixes it by making the enums non-packed again while keeping their manually added padding. It also fixes integer alignment bugs, which resurfaced when letting LLVM align the fields automatically again.
> Fix enum alignment loss bug.

- README.md
Changing the enumeration of libfuncs to have all the same index will fix merge conflicts while not affecting the compiled markdown because it'll be fixed automatically.
> Fix future merge conflicts in `README.md`.

- README.md
Some libfuncs where already done but still placed on todo on the readme, this moves them to the done section.
> move missed libfuncs on readme

- Cargo.lock
- src/lib.rs
The latest nightly Rust versions broke this project due to:
- A broken dependency (`thiserror`).
- A removed feature (`provide_any`).
The `provide_any` feature has been removed since it seems we weren't using it anymore. The dependency has just been updated to the latest version, along with a few others.
> Fix builds using the latest nightly rust versions.

- examples/erc20.rs
- examples/starknet.rs
- src/metadata/syscall_handler.rs
- src/starknet.rs
In order to modify state, some StarknetSyscallHandler trait methods have to receive a mutable reference to self.
Also, this PR removes the PhantomData used in the SyscallHandlerMeta for the lifetime
> Make StarknetSyscallHandler trait receive mut self for integration with SiR

- README.md
Added a badge with a link to the Lambda Starknet telegram group
> Add telegram channel link in README.md

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- examples/erc20.rs
- examples/starknet.rs
- programs/erc20.cairo
- programs/examples/hello_starknet.cairo
- scripts/test-erc20.sh
- src/bin/cairo-native-dump.rs
- src/debug_info/statements.rs
- src/starknet.rs
- Allows cairo-native-dump to compile contracts passing the --starknet flag.
- Removed the erc20.sierra, we can now test with the erc20.cairo program directly.
- Fixed the starknet example with a real simple contract.
- Pass gas to syscalls because some need it to do some checks or substract from it.
> Pass gas to syscalls, fix examples, allow cairo-native-dump to compile contracts

- Cargo.lock
- src/utils.rs
- tests/common.rs
- tests/programs.rs
- tests/starknet/contracts/test_keccak.cairo
- tests/starknet/keccak.rs
- tests/starknet/mod.rs
This will help greatly the development of the syscalls in starknet_in_rust
> initial contract test framework

- .github/workflows/bench-hyperfine.yml
- .github/workflows/ci.yml
- examples/erc20.rs
- examples/starknet.rs
- src/starknet.rs
- tests/starknet/keccak.rs
I think most methods need to take &mut self to be implemented in sir.
> starknet: make more methods take mut self

- examples/erc20.rs
- examples/starknet.rs
- src/execution_result.rs
- src/libfuncs/stark_net.rs
- src/starknet.rs
- src/utils.rs
- tests/common.rs
- tests/starknet/keccak.rs
Fixes gas so that the syscalls return the gas consumed.
Gas is now also properly handled in the NativeExecutionResult deserializer.
Use NativeExecutionResult in the tests and examples.
> fix gas in starknet syscalls, improve and use NativeExecutionResult

- src/execution_result.rs
Avoid panicking (and thus causing sometimes a segfault) when deserializing a native execution result
Small isolated PR I extracted from #327
It makes it so it doesnt panic and returns a deserialization error
> Avoid panicking when deserializing a native execution result

- src/execution_result.rs
- src/libfuncs/stark_net.rs
- tests/starknet/keccak.rs
Gas consumed is calculated on the SiR part, not here, got confused about that.
> revert back to remaining_gas for syscalls

- env-macos.sh
Following the MacOs setup in the Getting Started section of the README leads to an error when running `make test` as the env var `LLVM_SYS_170_PREFIX` is not set. This PR adds this export to the env-macos.sh script.
> Add `LLVM_SYS_170_PREFIX` export to env-macos.sh

- src/libfuncs/struct.rs
- tests/cases.rs
- tests/cases/structs/struct_snapshot_deconstruct.cairo
The implementation of `struct_deconstruct` libfunc already handles snapshots of structs propperly, so this PR is quite short
> Implement `struct_snapshot_deconstruct` libfunc

- README.md
There is no `poseidon` libfunc, there is a `hades_permutation` libfunc used in the poseidon core library module which is already implemented
> Update libfuncs list (poseidon)

- tests/alexandria.rs
- tests/alexandria/src/lib.cairo
The functions `karatsuba` & `aliquot_sum` cause the vm to run out of memory and cairo native to fail with a stack overflow error when big numbers are used
> Use smaller numbers in alexandria_math tests

- benches/libfuncs.rs
Libfunc is now implemented so we don't need to skip it's benchmark
> Don't skip `felt252_div` benchmark

- src/cache.rs
The structs and methods in both of these modules are public but their modules are not. This makes it impossible to create a `PorgramCache` from starknet_in_rust
> Make `cache::aot` & `cache::jit` modules public

- Cargo.lock
- Cargo.toml
- Makefile
- benches/benches.rs
- runtime/Cargo.toml
- src/bin/cairo-native-compile.rs
- src/bin/cairo-native-dump.rs
- src/bin/cairo-native-run.rs
- src/libfuncs/cast.rs
- src/libfuncs/nullable.rs
- src/libfuncs/sint16.rs
- src/libfuncs/uint256.rs
- src/utils.rs
- tests/common.rs
Bumps the cairo compiler dependency to 2.4.1.
> dev: bump cairo compiler

- .github/pull_request_template.md
I feel that by default it adds too much text, this makes the text meant as an explanation for the write only visible in edit mode.
> make PR template less verbose

- tests/cases/enums/enum_init_c_style.cairo
- tests/cases/enums/enum_init_empty.cairo
- tests/cases/enums/enum_init_multiple.cairo
- tests/cases/enums/enum_init_nested_c_style.cairo
- tests/cases/enums/enum_init_nested_empty.cairo
- tests/cases/enums/enum_init_nested_multiple.cairo
- tests/cases/enums/enum_init_nested_single_scalar.cairo
- tests/cases/enums/enum_init_nested_single_struct.cairo
- tests/cases/enums/enum_init_nested_single_tuple.cairo
- tests/cases/enums/enum_init_single_scalar.cairo
- tests/cases/enums/enum_init_single_struct.cairo
- tests/cases/enums/enum_init_single_tuple.cairo
- tests/tests/cases.rs
> Further enum init testing

- src/libfuncs/array.rs
There is an inline memcpy with a dynamic length, which is invalid.
> Fix memcpy with dynamic length

- src/bin/cairo-native-test.rs
- src/executor.rs
- src/libfuncs/cast.rs
- src/types.rs
- src/utils.rs
- src/values.rs
Casting now works with `bytes31` too.
> Fix casting libfuncs.

- src/execution_result.rs
When returning an error, the error message was formed from only the first element of the segment. This updates the errors message to include all elements.
> Improve error reporting

- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/rustdoc.yml
- Cargo.toml
- README.md
This allows so that when we make a tag matching `v*.*.*` a release page will be created and the artifacts uploaded.
It will also upload the crates to the crates.io registry using the `CARGO_REGISTRY_TOKEN` secret configured on this repository
> Add release and publish to the CI

- src/starknet.rs
- tests/tests/starknet/mod.rs
- tests/tests/starknet/programs/syscalls.cairo
- tests/tests/starknet/syscalls.rs
> Fix syscall handler glue code array conversions.

- src/starknet.rs
- tests/tests/starknet/syscalls.rs
> Fix `alloc_mlir_array`.

- Cargo.lock
- Cargo.toml
- src/compiler.rs
- src/libfuncs/array.rs
- src/libfuncs/box.rs
- src/libfuncs/gas.rs
- src/libfuncs/pedersen.rs
- src/libfuncs/uint128.rs
- src/types/array.rs
- src/types/nullable.rs
> dont use call_intrinsic, use the intrinsic directly

- src/bin/cairo-native-run.rs
- src/libfuncs/array.rs
- src/libfuncs/snapshot_take.rs
- src/metadata/debug_utils.rs
- src/metadata/snapshot_clones.rs
- src/types/array.rs
- src/types/nullable.rs
realloc was called with a size of 0 if the array was empty, which is implementation defined before C23 and UB from C23 onwards
> Dont call realloc on snapshot_take if array is empty, add some tests

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
Bump `starknet-types-core` to v0.1.0
> Bump `starknet-types-core` to v0.1.0

- src/block_ext.rs
- src/lib.rs
- src/libfuncs/array.rs
- src/libfuncs/function_call.rs
- src/libfuncs/sint128.rs
- src/libfuncs/sint16.rs
- src/libfuncs/sint32.rs
- src/libfuncs/sint64.rs
- src/libfuncs/sint8.rs
- src/libfuncs/uint128.rs
- src/libfuncs/uint16.rs
- src/libfuncs/uint32.rs
- src/libfuncs/uint64.rs
- src/libfuncs/uint8.rs
We have a lot of repeated places in codegen where we use complicated or repetitive operations, this refactors some common complexity so we can avoid mistakes.
For now I only use the methods in a few places like the array libfuncs, but it could be used in all libfuncs, It's just quite some more work to do replacing those.
Operations that are in BlockExt that can be replaced
- llvm.alloca
- arith.constant
- llvm.extract_value
- llvm.insert_value
- llvm.alloca
- llvm.load
- llvm.store
- llvm.memcpy
> Refactor common operations into a block trait

- src/libfuncs/bitwise.rs
- [ #520.] Linked to Github Issue
> bitwise refactored

- src/types.rs
> Fix layout paddings.

- src/types.rs
> Add test for layout paddings.

- cairo-tests/src/array_test.cairo
- cairo-tests/src/byte_array_test.cairo
- cairo-tests/src/dict_test.cairo
- cairo-tests/src/fmt_test.cairo
- cairo-tests/src/panics_test.cairo
> Unignore fixed tests.

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
- src/libfuncs/felt252_dict.rs
- src/metadata/runtime_bindings.rs
- src/types/felt252_dict.rs
- src/types/gas_builtin.rs
- src/types/nullable.rs
- src/utils.rs
- tests/common.rs
- tests/tests/alexandria.rs
- tests/tests/cases.rs
- tests/tests/dict.rs
> fix: dict gas

- src/libfuncs/mem.rs
> Refactor mem libfuncs to use the BlockExt trait

- cairo-tests/src/ec_test.cairo
- src/libfuncs/uint256.rs
Should close https://github.com/lambdaclass/cairo_native/issues/468
The modular inverse should be obtained roughly via the pseudo code:
```
function inverse(a, n)
t := 0;     newt := 1
r := n;     newr := a
while newr ≠ 0 do
quotient := r div newr
(t, newt) := (newt, t − quotient × newt) 
(r, newr) := (newr, r − quotient × newr)
if r > 1 then
return "a is not invertible"
if t < 0 then
t := t + n
return t
```
In the `build_u256_guarantee_inv_mod_n` construction, we missed the `t < 0` condition, causing this operation https://github.com/starkware-libs/cairo/blob/afeeed29b37bd394535fcf3e8d7d16db047381fb/corelib/src/ecdsa.cairo#L143 to fail in the ECDSA `recover_public_key` procedure. This issue is fixed and another unit test is added in the `u256_inv_mod_n` suite to cover this scenario.
> Fix `test_ecdsa_recover_public_key` test

- Cargo.lock
- Cargo.toml
- cairo-tests/src/keccak_test.cairo
- cairo-tests/src/lib.cairo
- cairo-tests/src/plugins_test.cairo
- cairo-tests/src/print_test.cairo
- cairo-tests/src/testing_test.cairo
- runtime/Cargo.toml
- src/bin/cairo-native-test.rs
- src/libfuncs/enum.rs
With this change, all the corelib tests can be ran, although some fail, but beforehand the test runner itself crashed due to missing a starknet syscall handler.
These are the remanining corelib tests that fail:
```
core::test::integer_test::proper_cast - Panicked with 0x4f7074696f6e3a3a756e77726170206661696c65642e ('Option::unwrap failed.').
core::test::integer_test::special_casts::test_bounded_int_casts - Panicked with 0x4f7074696f6e3a3a756e77726170206661696c65642e ('Option::unwrap failed.').
core::test::secp256k1_test::test_secp256k1_recover_public_key - Panicked with 0x4f7074696f6e3a3a756e77726170206661696c65642e ('Option::unwrap failed.').
core::test::secp256k1_test::test_verify_eth_signature - Panicked with 0x4f7074696f6e3a3a756e77726170206661696c65642e ('Option::unwrap failed.'). …
```
> Enable more corelib tests

- src/bin/cairo-native-compile.rs
- src/bin/cairo-native-run.rs
- src/bin/cairo-native-test.rs
- src/executor.rs
- src/ffi.rs
- src/utils.rs
- Small refactor
- Implementation of (in order to reduce duplicated code):
- `From<usize> for OptLevel`
- `Into<usize> for OptLevel`
- `From<u8> for OptLevel`
> Small refactor and util for `OptLevel`

- src/libfuncs/bool.rs
Refactored bool libfuncs to use BlockExt
> Refactor bool to use BlockExt

- src/compiler.rs
- src/metadata/gas.rs
- tests/alexandria/src/lib.cairo
- tests/tests/alexandria.rs
Fixes the last gas mismatch test left in Alexandria test suite. The builtins gas cost was not added to the `GasCost` metadata, which caused the mismatch. As shown [here](https://github.com/starkware-libs/cairo/blob/v2.5.4/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs#L150), builtins cost should be accounted for when calling the `withdraw_all_gas` libfunc.
> fix: builtin gas

- .dockerignore
- cairo-tests/src/math_test.cairo
> test: uncomment passing test

- Cargo.lock
- Cargo.toml
- src/debug_info.rs
> add unit test for `DebugInfo::extract`

- .github/workflows/ci.yml
> use github macos m1 runner

- Cargo.lock
- src/error.rs
- Useless `make_unexpected_value_error` function is removed.
- Unit test is provided for `make_missing_parameter` function.
> refactor `Error` and increase test coverage

- Cargo.lock
- Cargo.toml
- src/cache/aot.rs
- src/executor/aot.rs
- src/utils.rs
Adds test for AOT. Solves #481.
> test: unit aot

- Cargo.lock
- src/libfuncs/cast.rs
It used a sign extend when it should use a zero extend. The bug was that we checked whether to use sext if either src or dst type are signed when we should only care about src type
> Fix wrong upcast from unsigned to signed

- Cargo.lock
- src/bin/cairo-native-test.rs
Increase test coverage of `cairo-native-test`:
- secp256r1 operations
- secp256k1 operations
> increase test coverage of `cairo-native-test`

- src/bin/cairo-native-test.rs
The `--ignored` flag in `cairo-native-test` was not working as expected. It filtered out not ignored tests, but left the ignored tests as "ignored" (so no tests were executed in the end).
This PR fixes the issue by not only filtering out not ignored tests, but also changing the status of the remaining tests to "not ignored".
Also, the function now is separated in different iterator chains to improve legibility
> Fix Ignored Flag Bug

- Cargo.lock
- src/executor.rs
- tests/cases/cairo_vm/felt_dict_squash.cairo
- tests/common.rs
- tests/tests/cases.rs
> add `SquashedFelt252Dict` in executor

- README.md
- src/executor.rs
- src/libfuncs/felt252_dict_entry.rs
- src/starknet.rs
Applies the comments from https://github.com/lambdaclass/cairo_native/pull/566#pullrequestreview-2071782858
> Apply missed fixes on llvm 18 pr

- .github/workflows/bench-hyperfine.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/rustdoc.yml
- src/bin/utils/test.rs
This is a fix extracted from #622 but without the corelib yet, since i still need to investigate the corelib issues, but this is ready to merge
> fix test syscall handler secp operations

- src/libfuncs/uint16.rs
> Refactored u16 to use the BlockExt trait

- src/libfuncs/function_call.rs
> Refactored function call libfuncs to use the BlockExt trait

- src/block_ext.rs
- src/libfuncs/array.rs
- src/libfuncs/ec.rs
- src/libfuncs/enum.rs
- src/libfuncs/felt252_dict_entry.rs
- src/libfuncs/function_call.rs
- src/libfuncs/pedersen.rs
- src/libfuncs/starknet.rs
- src/types/box.rs
> Refactored pedersen libfuncs to use the BlockExt trait

- src/libfuncs/felt252_dict.rs
> Refactored felt252 dict libfuncs to use the BlockExt trait

- src/libfuncs/sint8.rs
> Refactored sint8 to use the BlockExt trait

- src/libfuncs/sint32.rs
> Refactored sint32 to use the BlockExt trait

- src/libfuncs/dup.rs
- tests/tests/cases.rs
> Fix `dup` implementation for `Box<T>` and other non-copy types.

- src/error.rs
- src/libfuncs/cast.rs
`SierraAssert` errors are grouped into a `SierraAssertError` enum in order to avoid string errors and have clearer patterns.
> add `SierraAssertError` enum

- .gitignore
- Cargo.lock
- Cargo.toml
- src/bin/cairo-native-stress.rs
- src/libfuncs/uint64.rs
related to #682
Adds `cairo-native-stress` that generates, compiles, caches, and runs contracts in order to stress test cairo native.
- Receives by argument the amount rounds to execute.
- In each round it generates, compiles, caches, and runs a new contract
- The compiled dynamic shared libraries are stored on disk
- The cache keeps in memory every executor for every compiled contract
- After each round, it prints a report
At the start of the program, a dummy program is generated with a hardcoded value (835 in this case) in the return value:
```cairo
#[starknet::contract]
mod Contract {
#[storage]
struct Storage {}
#[external(v0)]
fn main(self: @ContractState) -> felt252 {
return 835;
}
}
```
At the start of each round, the program is traversed to find the hardcoded value and is replaced …
> Basic Stress Test

- src/error.rs
- src/executor/aot.rs
- src/executor/jit.rs
- src/metadata/gas.rs
The `InsufficientGasError` inside the `Error` enum actually internally represents a `GasMetadataError` `NotEnoughGas` error.
It is therefore more practical and idiomatic to group these errors around `GasMetadataError` with a more explicit message on the `NotEnoughGas` error specifying the gases required and the gases available to give more information to the user.
Part of https://github.com/lambdaclass/cairo_native/issues/632
> improve gas error

- src/block_ext.rs
- src/libfuncs/array.rs
- src/libfuncs/const.rs
- src/libfuncs/ec.rs
- src/libfuncs/enum.rs
- src/libfuncs/felt252_dict_entry.rs
- src/libfuncs/function_call.rs
- src/libfuncs/pedersen.rs
- src/libfuncs/poseidon.rs
- src/libfuncs/starknet.rs
- src/libfuncs/starknet/secp256.rs
- src/libfuncs/starknet/testing.rs
- src/metadata/debug_utils.rs
- src/types/array.rs
- src/types/box.rs
All alloca operations need the target alignment. Load and store operations don't need it because the pointer is already aligned (or should be). This PR makes the alignment mandatory on allocas and removes it on load and store operations.
> Fix alloca, load and store operations on `BlockExt`.

- .github/workflows/bench-hyperfine.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/rustdoc.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- Makefile
- README.md
- env.sh
- runtime/Cargo.toml
The env var for llvm changed to `LLVM_SYS_181_PREFIX`
> Update to cairo 2.6.4 and update LLVM env var

- src/executor.rs
- src/types/array.rs
Currently, `snapshot_take` only deep-clones the first element of the array, causing segfaults in some cases and invalid data in others. This PR fixes that.
> Fix `snapshot_take` for arrays.

- README.md
Fixes #708
Updates the command to compile from MLIR to binary in `README.md`. Might have been missed during name change to cairo native
> docs: fix mlir to binary section

- src/executor.rs
> Remove std::mem::forget(arena) on invoke_dynamic

- src/arch.rs
- src/arch/aarch64.rs
- src/arch/x86_64.rs
- src/executor.rs
- src/lib.rs
- src/metadata/debug_utils.rs
- src/values.rs
- tests/tests/trampoline.rs
- Fixes `to_jit()` for arrays (we didn't notice because we weren't using it before).
- Completely replaces `ArgumentMapper` with a more intuitive system that can integrate multiple architectures easily.
- Fixes the `Failed to deserialize param #1` error.
- Fixes a bug in our debug utils `print_felt252`.
- Makes `JitValue::Felt(_)`'s `std::fmt::Debug` implementation print the real value instead of its Montgomery form limbs.
- Adds a test to check if the circumstances that caused this bug happens in the future.
> Refactor `ArgumentMapper` to fix bugs in ARM.

- src/libfuncs/enum.rs
- src/metadata.rs
- src/metadata/auto_breakpoint.rs
- src/metadata/debug_utils.rs
This PR adds a semi-automatic breakpoint utility that allows (for now) to:
- Automatically pause execution (when debugging) when executing `enum_init` on a specific enum and variant.
It's useful, for example, to automatically stop when a panic is triggered.
> Add auto-breakpoint utility.

- .github/workflows/bench-hyperfine.yml
- .github/workflows/ci.yml
- Dockerfile
> Fix CI (attempt #2).

- src/arch.rs
- src/libfuncs/box.rs
- src/libfuncs/nullable.rs
- src/types.rs
- tests/tests/trampoline.rs
Something I missed from the previous fix.
> Fix `Box<T>` and `Nullable<T>` as entry point arguments.

- src/libfuncs/array.rs
Implements new array libfuncs from cairo lang 2.7.0:
- `tuple_from_span`: converts a span to a fixed size tuple if the size matches
- `snapshot_multi_pop_front`: pops elements from the front of a span and returns them as a fixed array
- `snapshot_multi_pop_back`: pops elements from the back of a span and returns them as a fixed array
> Implement new array libfuncs.

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
While integrating cairo `2.7.0-rc.3` to the [blockifier](https://github.com/NethermindEth/blockifier/pull/121), we've got a dependency error with incorrect `starknet-types-core` version. Also while executing new CI after the update, we've found out that `cairo-lang-runner` is not being used in the `cairo-native-runtime` crate, so we've removed it.
> Update version of `starknet-types-core` and remove unused dependencies  

- Cargo.lock
- runtime/Cargo.toml
Machete (https://github.com/bnjbvr/cargo-machete) found that `cairo-lang-runner` is not used in `cairo-native-runtime`, so I've removed it from the dependencies
> remove unused dep: `cairo-lang-runner` from `cairo-native-runtime`

- src/executor/aot.rs
- src/ffi.rs
Previously when using AOT the llvm ir was not optimized, in JIT if you pass the optlevel it internally optimizes the llvm ir but with AOT we have to do it ourselves.
> Optimize AOT 

- src/ffi.rs
> Limit llvm ir optimizer to O1 max due to bug in llvm

- src/executor/contract.rs
Fixes the comment in https://github.com/NethermindEth/sequencer/pull/14#issuecomment-2346748350
> Fix missing zero sized builtin in match on ContractExecutor

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
Changes runtime to use starknet_types_core rather than starknet_crypto. This doesn't affect performance, as starknet_crypto uses starknet_types_core in its implementation
> Use starknet_types_core pedersen and hades permutation

- benches/compile_time.rs
- benches/libfuncs.rs
- examples/easy_api.rs
- examples/erc20.rs
- examples/invoke.rs
- examples/starknet.rs
- src/bin/cairo-native-compile.rs
- src/bin/cairo-native-dump.rs
- src/bin/cairo-native-run.rs
- src/bin/cairo-native-stress/main.rs
- src/bin/scarb-native-dump.rs
- src/bin/utils/test.rs
- src/cache/aot.rs
- src/cache/jit.rs
- src/compiler.rs
- src/context.rs
- src/executor.rs
- src/executor/aot.rs
- src/executor/contract.rs
- src/executor/jit.rs
- src/libfuncs/enum.rs
- src/libfuncs/function_call.rs
- src/utils.rs
- tests/common.rs
- tests/tests/compile_library.rs
- tests/tests/trampoline.rs
Add option to never have debug names in functions and enable it on ContractExecutor, fix dangling temp library file
> ContractExecutor changes

- Makefile
https://github.com/software-mansion/scarb/releases/tag/v2.8.3
it uses cairo 2.8.2 still
> update scarb in makefile

- src/libfuncs/dup.rs
- src/metadata/enum_snapshot_variants.rs
- src/metadata/snapshot_clones.rs
- src/types/snapshot.rs
> Fix snapshot clones

- src/libfuncs/cast.rs
Fixes #821
Apparently in cairo you can downcast a smaller type into a bigger type (even both being non bounded ints), the code was already in place to handle this conversion (only needed to remove a unreachable and handle that path, i added a comment there).
> Remove assert on downcast, fixing a panic

- Cargo.toml
- runtime/src/lib.rs
- src/libfuncs/array.rs
- src/libfuncs/drop.rs
- src/libfuncs/dup.rs
- src/libfuncs/felt252_dict.rs
- src/libfuncs/snapshot_take.rs
- src/metadata.rs
- src/metadata/drop_overrides.rs
- src/metadata/dup_overrides.rs
- src/metadata/enum_snapshot_variants.rs
- src/metadata/runtime_bindings.rs
- src/metadata/snapshot_clones.rs
- src/types.rs
- src/types/array.rs
- src/types/box.rs
- src/types/enum.rs
- src/types/felt252_dict.rs
- src/types/non_zero.rs
- src/types/nullable.rs
- src/types/snapshot.rs
- src/types/struct.rs
- src/utils.rs
- src/values.rs
- tests/tests/programs.rs
**Changes**
- Rename a few things.
- Remove `SnapshotClonesMeta`.
- Remove old drop implementation system.
- Add `DupOverridesMeta` (successor of `SnapshotClonesMeta`) and `DropOverridesMeta`.
- Make all types that require it use the new dup and drop systems.
- Refactor some dict methods to make them work with the new dup and drop system.
> Fix clone and drop implementations for enums, structs and snapshots

- src/libfuncs/array.rs
I implemented an `if` statement backwards. This PR fixes it.
> Fix `array_get`'s drop implementation.

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- docs/release.md
- env.sh
- runtime/Cargo.toml
- src/arch.rs
- src/error.rs
- src/executor.rs
- src/ffi.rs
- src/values.rs
This PR updates cairo to 2.8.4, adds some release docs and updates the version to alpha.3 to prepare for another release.
It also removes a possible panic in case linking fails and renames from_jit and to_jit to from_ptr and to_ptr
> Update to 2.8.4, add release docs, version alpha.3

- .github/workflows/bench-hyperfine.yml
- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
- src/executor.rs
- src/executor/contract.rs
- src/values.rs
Some types, including at least `felt252` and most enum's tags, have a deserialization bug where the bytes that are not part of the type in MLIR are also parsed as part of the value in Rust. This PR filters out those bits.
> Fix felt252 and enum deserialization bugs.

- src/starknet.rs
Fixes https://github.com/lambdaclass/cairo_native/issues/845, in conjunction with https://github.com/lambdaclass/sequencer/pull/11.
`wrap_sha256_process_block` syscall should modify the received state with the new state, but instead of doing this, it copies the value and modifies the copied version, leaving the old state untouched.
This PR fixes it.
All transactions mentioned in the issue are now working correctly.
> Fix process block bug

- src/starknet.rs
Related to https://github.com/lambdaclass/cairo_native/pull/844 but it missed some starknet syscalls
Refactored a bit the code to avoid some repetition.
This may fix some bugs we have, we need to test.
> Also fix felt bits in starknet syscall wrappers

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
> Update version to alpha 4

- docs/execution_walkthrough.md
- scripts/bench-hyperfine.sh
- src/ffi.rs
Simple PR to resolve the `CAIRO_NATIVE_RUNTIME_LIBRARY` when it is a relative path so that it can work better with STARKNET approach to global vars (e.g. doing "./native_runtime.a") will turn into "/usr/somewhere/over/the/rainbow/native_runtime.a".
Looking forward to hear your thoughts!
> Resolve `CAIRO_NATIVE_RUNTIME_LIBRARY` relative path

- runtime/Cargo.toml
- runtime/src/lib.rs
- tests/common.rs
- tests/tests/boolean.rs
> Add runtime tests

- programs/benches/factorial_2M.c
- programs/benches/fib_2M.c
- programs/benches/logistic_map.c
- src/compiler.rs
- src/error.rs
- src/executor.rs
- src/executor/aot.rs
- src/executor/contract.rs
- src/executor/jit.rs
- src/libfuncs/gas.rs
- src/metadata/gas.rs
- src/types.rs
- src/types/builtin_costs.rs
- src/utils.rs
- src/values.rs
- tests/common.rs
* [Revert "fix aot contract executor not passing builtinstats (](https://github.com/lambdaclass/cairo_native/commit/e2f895c707acf0b5c74fe42eb3d076f4cebfe4f2)https://github.com/lambdaclass/cairo_native/pull/849[)"](https://github.com/lambdaclass/cairo_native/commit/e2f895c707acf0b5c74fe42eb3d076f4cebfe4f2)
* [Revert "Builtin costs rework (](https://github.com/lambdaclass/cairo_native/commit/9dffb6165200f90263fee24e1db4d90a85a89fd0)https://github.com/lambdaclass/cairo_native/pull/837[)"](https://github.com/lambdaclass/cairo_native/commit/9dffb6165200f90263fee24e1db4d90a85a89fd0)
We need to revert this changes, because they are causing some errors when re-executing blocks in Starknet Replay
> Revert builtin cost rework

- .github/workflows/bench-hyperfine.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/rustdoc.yml
- rust-toolchain.toml
- src/executor.rs
> Update rust to 1.82.0

- Makefile
- examples/erc20.rs
- examples/starknet.rs
- src/libfuncs/starknet.rs
- src/starknet.rs
- src/starknet_stub.rs
- tests/tests/starknet/programs/syscalls.cairo
- tests/tests/starknet/secp256.rs
- tests/tests/starknet/syscalls.rs
> Implement get_class_hash_at syscall

- .github/workflows/starknet-blocks.yml
> Fix block workflow

- .github/workflows/starknet-blocks.yml
- src/error.rs
- src/executor/contract.rs
- src/utils.rs
- tests/common.rs
- tests/tests/starknet/keccak.rs
This also allows us to filter out methods that are not contract entry points, making the JSON file significantly smaller.
Depends on #875 
Fixes #885
> Add entry point info to AotContractExecutor

- Cargo.lock
- src/libfuncs/felt252.rs
Fixes `felt_const` libfunc, which was producing errors when was given negative values as parameters.
Closes #887
> fix felt_const libfunc

- docs/sierra.md
Including:
- Gas accounting
- Cairo and Sierra links
> Add more Sierra links

- src/bin/cairo-native-run.rs
- src/compiler.rs
- src/error.rs
Adds a new error type: `NativeAssertError`. It's a replacement for panic!, as it collects the backtrace but it doesn't interrupt the flow of the program.
There is a single `todo!` left, but I didn't know how to deal with it. We should take a closer look at it.
There are a few `expect` left, but being such a simple case, I'm not sure is worth handling it.
Unlike #905, I tried to make this non-panic abstraction as similar as possible to the associated panicking code. The compiler.rs was changed to use the non-panic variants
> Remove panic from compiler.rs (2)

- src/compiler.rs
- src/error.rs
- src/libfuncs.rs
- src/libfuncs/array.rs
- src/libfuncs/bounded_int.rs
- src/libfuncs/cast.rs
- src/libfuncs/const.rs
- src/libfuncs/debug.rs
- src/libfuncs/enum.rs
- src/libfuncs/felt252_dict_entry.rs
- src/libfuncs/function_call.rs
- src/libfuncs/gas.rs
- src/libfuncs/starknet.rs
> Remove panics in libfuncs

- benches/util.rs
- examples/easy_api.rs
- examples/invoke.rs
- src/bin/cairo-native-compile.rs
- src/utils.rs
There are some unwraps left, but they are only used in tests.
`get_integer_layout` will never fail, and adding error handling implies changing a lot of files, as it's used throughout the codebase. We can consider changing it later.
The file `utils/mem_tracing.rs` also contains some unreachable, but as it's a debugging feature I don't think it's worth to update it.
> Remove panic in utils.rs

- src/arch.rs
- src/executor.rs
> Remove panics in arch.rs

- .github/workflows/starknet-blocks.yml
- Cargo.lock
- benches/compile_time.rs
- benches/libfuncs.rs
- examples/easy_api.rs
- examples/erc20.rs
- examples/invoke.rs
- examples/starknet.rs
- src/bin/cairo-native-compile.rs
- src/bin/cairo-native-dump.rs
- src/bin/cairo-native-run.rs
- src/bin/cairo-native-stress/main.rs
- src/bin/scarb-native-dump.rs
- src/bin/utils/test.rs
- src/cache/aot.rs
- src/cache/jit.rs
- src/context.rs
- src/executor.rs
- src/executor/aot.rs
- src/executor/contract.rs
- src/libfuncs/enum.rs
- src/utils.rs
- tests/common.rs
- tests/tests/compile_library.rs
- tests/tests/starknet/keccak.rs
- tests/tests/trampoline.rs
Removes the initial gas cost calculations and substractions, the caller will handle it.
> Remove gas accounting from AotContractExecutor

- env.sh
This PR allows `env.sh` to be used from any directory, not just the cairo native project's root. This is useful for setting up the environment in other projects (ex. the replay) painlessly.
> Fix `env.sh`.

- src/libfuncs/array.rs
- src/types/array.rs
- Adds comments to make the code easier to understand.
- Renames a few variables with clearer names.
- Fixes a minor bug. We were not calculating the array allocation pointer correctly. It was fixed by properly naming variables.
> Improve array documentation (and minor bug)

- rust-toolchain.toml
- src/arch.rs
- src/cache/aot.rs
- src/cache/jit.rs
- src/executor/jit.rs
- src/libfuncs.rs
- src/libfuncs/function_call.rs
- src/types.rs
> Update rust to 1.83.0

- Cargo.toml
- src/arch.rs
- src/error.rs
- src/utils.rs
- src/values.rs
A few issues were preventing minimal builds from succeeding:
- Some binary-only libraries had crept onto the library.
- We were missing some conditional compilation flags.
All those issues have been fixed.
> Fix `--no-default-features` library-only builds.

- runtime/src/lib.rs
- src/executor/aot.rs
- src/executor/contract.rs
For now it'll panic with an assert. It is the user's responsibility to clear the contract cache when upgrading.
> Add version check for cached AOT contracts.

- src/libfuncs/array.rs
Array clones caused by an invocation of `array_snapshot_pop_front` over shared arrays were cloning data from an incorrect pointer.
> Fix `array_snapshot_pop_front` CoW clones.

- .github/workflows/daily.yml
As the replay and sequencer crates now use Cairo Native tags, we must manually update the dependencies instead of relying on cargo.toml patches. 
We are not currently using latest main on the daily run, only the specified release, as this warning says:
> warning: Patch `cairo-native v0.2.5 (/home/runner/work/cairo_native/cairo_native/cairo_native)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
With this PR, the daily workflow:
- Clones all the needed repositories
- Updates all dependencies to point to …
> Fix daily run dependencies

- runtime/src/lib.rs
> Fix possible segfault when checking runtime's version

- .github/workflows/starknet-blocks.yml
> Update replay's version in blocks workflow ci

- .github/workflows/bench-hyperfine.yml
- .github/workflows/ci.yml
- .github/workflows/daily.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/rustdoc.yml
- .github/workflows/starknet-blocks.yml
- rust-toolchain.toml
- tests/common.rs
> update rust to 1.84.0

- .github/workflows/daily.yml
- .github/workflows/starknet-blocks.yml
We were caching whole cairo_native directory, instead of the target directory. This implied:
- Sometimes the wrong version was used
- The contracts were being cached
> Fix CI Cache: only cache cairo native target

- Cargo.toml
- runtime/Cargo.toml
Avoids updating `cairo-lang` to 2.10.0-rc1. We need to adapt Native to that new version first.
> Pin cairo-lang to 2.10.0-rc0

- .github/workflows/ci.yml
- .github/workflows/starknet-blocks.yml
- Cargo.lock
- Cargo.toml
- Makefile
- runtime/Cargo.toml
- src/debug.rs
- src/libfuncs/bounded_int.rs
- src/libfuncs/const.rs
- tests/alexandria/Scarb.toml
The corelib includes test for these:
- https://github.com/starkware-libs/cairo/blob/85f06b92a3700ae7e18957ff3b29b903d612a3d8/corelib/src/test/language_features/const_test.cairo#L169
- https://github.com/starkware-libs/cairo/blob/3e72a692b4bb3d519b7cb5852fb8bc171deb9df9/corelib/src/test/integer_test.cairo#L2162
> Update cairo to 2.10.0-rc1

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
> bump version to 0.2.9 for release

- .github/workflows/bench-hyperfine.yml
I was getting triggered by this (image) and fixed it
> fix bench comment

- src/bin/utils/mod.rs
- src/compiler.rs
- src/executor.rs
- src/libfuncs/const.rs
- src/libfuncs/int.rs
- src/types/circuit.rs
> Remove missing todos

- src/executor/contract.rs
The `linear_gas_solver` and `linear_ap_change_solver` fields should only be set to `true` when the Sierra version is at least `1.4`.
Source: https://github.com/starkware-libs/cairo/blob/71d6052dd167ff9435873d30c52b5b0d10116b71/crates/cairo-lang-starknet-classes/src/casm_contract_class.rs#L412-L422
> TODO: Provide a way to specifiy the sierra version at `AotContractExecutor::new()`.
> Fix gas diffs.

- src/libfuncs/circuit.rs
Made it so its like https://github.com/starkware-libs/cairo/blob/v2.10.0-rc.1/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs
> Adjust circuit usage

- .github/workflows/daily.yml
If the job fails, the RPC Cache is not saved. This fixes this so that it is always saved.
Also, it removes Cairo Native runtime compilation, as its no longer used.
> Fix daily run cache

- .github/workflows/starknet-blocks.yml
- scripts/cmp_state_dumps.sh
- src/executor/contract.rs
- tests/common.rs
Adds a new argument to `AotContractExecutor::new` that allows for specifying the sierra version. It is used to correctly build the computation metadata.
Closes #1072
> Specify sierra version in Contract Executor

- src/libfuncs/array.rs
We had the same bug as #1063 when popping from the back. Not anymore.
> Fix `array_snapshot_pop_back`'s clone-on-write's clone implementation.

- .github/workflows/bench-hyperfine.yml
- .github/workflows/daily.yml
- .github/workflows/starknet-blocks.yml
> Update actions/cache to recommended version

- src/executor/contract.rs
When compiling contracts in our server, we encountered the following error: `IoError(Os { code: 18, kind: CrossesDevices, message: "Invalid cross-device link" })`.
This seems to happen when the temporary file used to compile contract is not in the same file system as the requested output path.
To fix this, instead of using a temporary file, the lockfile is used as a tmp file, and then renamed to the output path.
> Fix cross-device-link error when compiling contract

- Cargo.toml
- src/bin/starknet-native-compile.rs
PR is exactly like https://github.com/lambdaclass/cairo_native/pull/1091 but we have to fix external prs not being able to use secrets, for now i'll open the pr myself. (contribution attributions should still be correct in the git log)
> Add cli for sierra to native compilation in Starknet blockifier (ci permissions)

- .github/workflows/ci.yml
- .github/workflows/starknet-blocks.yml
- Cargo.lock
- Cargo.toml
- Makefile
- src/libfuncs/circuit.rs
- tests/alexandria/Scarb.lock
- tests/alexandria/Scarb.toml
> Bump Cairo version to 2.10.0

- Cargo.lock
- Cargo.toml
- README.md
To prepare for the incoming release
> bump version to 0.3.2

- rust-toolchain.toml
Bump Rust to 1.85
Closes #1114
> Bump Rust to 1.85

- src/executor/contract.rs
- src/libfuncs/array.rs
- src/values.rs
Removes some panics in Cairo Native
> Remove panics

- src/types/array.rs
- src/utils.rs
Change unwrap to expect in some unreachable panics, explaining why they will never fail.
> Improves documentation on unreachable panics

- src/libfuncs/array.rs
- src/libfuncs/bool.rs
- src/libfuncs/debug.rs
- src/libfuncs/enum.rs
- src/libfuncs/felt252_dict.rs
- src/libfuncs/gas.rs
- src/libfuncs/int.rs
- src/libfuncs/pedersen.rs
- src/libfuncs/poseidon.rs
- src/libfuncs/starknet.rs
This PR removes all panics in the libfuncs directory, by replacing it with native asserts.
> Remove panics from libfuncs directory

- src/libfuncs/felt252_dict_entry.rs
- src/metadata/runtime_bindings.rs
- src/runtime.rs
There was a bug in the dictionaries that caused the cloned pointer (when it had to be cloned) to not be updated, ending up with accesses to dangling pointers. This PR fixes that bug.
> Fix dictionary clones.

- docs/release.md
Removes instructions regarding the runtime, as we no longer have a separate crate.
Also adds instructions for generating the release notes.
> Update release docs

- src/runtime.rs
- tests/tests/dict.rs
The following program was failing because we were creating the allocating data for the dictionary using the original dictionary's length, rather that it's capacity.
```cairo
use core::dict::Felt252Dict;
fn main() {
let mut dict: Felt252Dict<u64> = Default::default();
for number in 0..50_u64 {
let snapshot = @dict;
let key = number.try_into().unwrap();
dict.insert(key, number);
drop(snapshot)
}
}
```
> Fix dictionary clone implementation

- src/arch.rs
- src/arch/aarch64.rs
- src/arch/x86_64.rs
- src/executor.rs
- src/executor/aot.rs
- src/executor/jit.rs
- src/libfuncs/felt252_dict.rs
- src/metadata/felt252_dict.rs
- src/metadata/runtime_bindings.rs
- src/runtime.rs
- src/types/felt252_dict.rs
- src/utils.rs
- src/values.rs
Depends on #1132
We found that dictionaries where unnecessarily cloned when modifying dictionaries that had snapshots. This could be avoided as dictionary snapshots are useless and thus do not need its internal representation to be inmutable.
The following code would waste a lot of memory:
```cairo
use core::dict::Felt252Dict;
fn main() {
let mut dict: Felt252Dict<u64> = Default::default();
for number in 0..100_u64 {
let snapshot = @dict;
let key = number.try_into().unwrap();
dict.insert(key, number);
drop(snapshot)
}
}
```
The easiest way to implement this is by removing the clone mechanism, but keep the reference counter.
- Remove the CoW mechanism: [d4c1aed](https://github.com/lambdaclass/cairo_native/commit/d4c1aed607accdc69a5dd7720a6001c84175ebbd) - this is the only commit required …
> Remove dictionary CoW mechanism

- Makefile
- src/bin/cairo-native-test.rs
We need to release a Cairo Native version, with Cairo v2.11.1. However, not all _libfunc_ introduced in that version are implemented yet, which makes the _corelib_ tests fail.
This PR adds a new flag to `cairo-native-test` called `--skip-compilation` that allows to skip the compilation of a test entirely, allowing us to merge the version bump into main without the need of implementing those _libfuncs_ yet.
The alternative to this solution is to add the corelib to the repository, commenting the failing tests. However, this would imply adding a lot of code (the entire corelib) into Native. We prefer not to do that.
This is a temporary solution and should be removed once those _libfuncs_ are implemented.
> [2.11.1] Ignore failing corelib tests

- src/libfuncs.rs
- src/libfuncs/gas.rs
- src/libfuncs/starknet.rs
- src/types.rs
- src/values.rs
Replace todo! with proper error handling
> [2.11.1] Replace todo! with proper error handling

- .github/workflows/ci.yml
- .github/workflows/starknet-blocks.yml
- Cargo.lock
- Cargo.toml
- Makefile
- README.md
This PR bumps cairo-lang's version to 2.11.2.
Closes #1155.
> Bump cairo lang to 2.11.2

- .github/workflows/ci.yml
Ubuntu 20.04 will be deprecated in Github Actions. For now the action is unstable.
See https://github.com/actions/runner-images/issues/11101 for further details.
> Remove Ubuntu 20.04 CI workflow

- src/libfuncs/starknet.rs
The layout for the return pointer of the `deploy` syscall was incorrect, which implied that on return it would overwrite part of the previous stack value.
- In this particular case, it would overwrite the return pointer for the _mlir ciface wrapper_.
- This caused a segfault at the end of the function, when trying to store the return arguments on the return pointer.
From [Layout::extend](https://doc.rust-lang.org/beta/std/alloc/struct.Layout.html#method.extend) documentation:
> In order to match C representation layout repr(C), you should call pad_to_align after extending the layout with all fields. (There is no way to match the default Rust representation layout repr(Rust), as it is unspecified.)
> Fix deploy syscall segfault :)

- src/error.rs
- src/libfuncs/circuit.rs
- src/values.rs
This PR fixes `into_u96_guarantee` libfunc so that it handles:
- BoundedInts with non zero lower range
- Smaller data types (like u8)
It used to be a noop because we though it always received an u96.
This PR fixes a bug in some contracts, caused by using an `u8` as input to this libfunc:
- `0x1aa0ae9d42edb490e438b161504f01b885e487f73d146a4d10baf78bb3f155`
- `0xc9e956f41095d8b61d7254e6955521121527ffbaad87c6475b71247aa009d4`
Note: Independly from the bug fix, i added a `#[track_caller]` attribute that was missing. It does not change the fix.
> Fix into_u96_guarantee not handling other types

- Cargo.lock
- Cargo.toml
- README.md
Bumps the crate version to 0.4.1, to make a bugfix release.
> v0.4.1: Prepare for Release

- Cargo.lock
- Cargo.toml
- src/bin/cairo-native-run.rs
- src/bin/utils/test.rs
- src/context.rs
- src/executor/contract.rs
- src/metadata/gas.rs
In Native, we had some [code copied from cairo-lang](https://github.com/lambdaclass/cairo_native/blob/c03e59ada0a0e210b96b51d7df186e2a6aec0fd1/src/metadata/gas.rs#L201-L218) that contained logic on how to construct the GasMetadata.
This logic got outdated, and caused some diffs when comparing with the CairoVM, which used the updated version of the gas metadata construction.
This PR removes the copied code and instead reuses the code directly as a dependency (from `cairo-lang-sierra-to-casm`), making sure that we use the exact same logic for constructing the metadata.
Fixes #1179
> Reuse cairo-lang GasMetadata calculations

- .github/workflows/starknet-blocks.yml
- Cargo.lock
- Cargo.toml
- Makefile
- debug_utils/sierra-emu/Cargo.toml
- debug_utils/sierra-emu/Makefile
- debug_utils/sierra-emu/src/debug.rs
- debug_utils/sierra-emu/src/vm.rs
- debug_utils/sierra-emu/src/vm/bounded_int.rs
- rust-toolchain.toml
- src/arch.rs
- src/debug.rs
- src/executor/contract.rs
- src/libfuncs.rs
- src/libfuncs/bounded_int.rs
- src/libfuncs/cast.rs
- src/libfuncs/circuit.rs
- src/libfuncs/gas.rs
- src/utils/sierra_gen.rs
- tests/tests/starknet/keccak.rs
- tests/tests/starknet/u256.rs
This PR bumps Cairo dependencies to v2.12.0-dev.1.
- Bounded int libfuncs are now gated under a feature.
- The `upcast` and `downcast` libfuncs are no longer exported, so we must declared them manually with `extern`.
- The gas usage is a bit different.
Bumping to this version requires bumping also the rust toolchain. This implies some changes that seem unrelated, in order to fix clippy lints.
This release adds a new libfunc: `unsafe_panic`.
> Bump to Cairo v2.12.0-dev.1

- .github/workflows/ci.yml
- src/error.rs
- src/libfuncs/circuit.rs
- src/values.rs
- tests/tests/circuit.rs
- Cherrypicks #1171
- Disable circuit libfuncs temporarily
- Ignore circuit tests
> [WIP] Temporary fix for 0.3.4 circuit bugs

- .github/workflows/ci.yml
- src/libfuncs/circuit.rs
- src/types/circuit.rs
- tests/tests/circuit.rs
This PR modifies the circuit implementation to use dynamic arrays, instead of static arrays.
This implies the following changes:
- Changed the type definition to use pointers instead of arrays
- Implemented `dup` and `drop` overrides for all requiring types
- Modified implementation of circuit libfuncs to take this into account.
For reviewing, I suggest first looking at the new type definitions, and then looking at the actual implementation changes.
This PR should also be applied to the main branch.
> v0.3.5: Use dynamic arrays instead of static arrays for circuit data

- src/values.rs
Rename tests that where still refering to method `to_jit()` that was renamed to `to_ptr()` in `value.rs`
> Update to_jit() -> to_ptr

- .github/workflows/daily.yml
- .github/workflows/starknet-blocks.yml
The last version of starknet-replay intoduces a series of binaries. Thus, we now need to specify which of them we are going to use. This wasn't updated in cairo native's ci, which caused its failure. 
Also, updated the starknet-replay's and sequencer's version in starknet-blocks workflow so that they match the ones in the daily workflow.
> Fix replay usage in blocks CI

- src/libfuncs/starknet.rs
Libfunc: `build_class_hash_try_from_felt252()`
- [Native](https://github.com/lambdaclass/cairo_native/blob/470083391c0c4a55e8860e1993389b0b029a53d1/src/libfuncs/starknet.rs#L384): increments the range_check builtin by 1
- [Compiler](https://github.com/starkware-libs/cairo/blob/a0bb22206ade04f065c84a12d6c2568ee98d325d/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L266): increments the range_check builtin by 3
**Changes**
- The libfunc now increments the range_check builtin by 3
> Fix build_class_hash_try_from_felt252() range_check increment

- src/libfuncs/starknet.rs
Libfunc: `build_storage_address_try_from_felt252()`
- [Native](https://github.com/lambdaclass/cairo_native/blob/470083391c0c4a55e8860e1993389b0b029a53d1/src/libfuncs/starknet.rs#L865): increments the range_check builtin by 1
- [Compiler](https://github.com/starkware-libs/cairo/blob/a0bb22206ade04f065c84a12d6c2568ee98d325d/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs#L266): increments the range_check builtin by 3
**Changes**
- The libfunc now increments the range_check builtin by 3
> Fix build_storage_address_try_from_felt252() range_check increment

- src/libfuncs/int.rs
- [Native](https://github.com/lambdaclass/cairo_native/blob/470083391c0c4a55e8860e1993389b0b029a53d1/src/libfuncs/int.rs#L506): counts range_check 1 time
- [Compiler](https://github.com/starkware-libs/cairo/blob/96625b57abee8aca55bdeb3ecf29f82e8cea77c3/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L32):  counts range_check 9 times.
> Fix `uint128_mul_guarantee_verify` range check counting

- src/libfuncs/box.rs
To imitate the CASM compiler, this libfunc should not increment builtin counters.
- [Sierra to CASM code](https://github.com/starkware-libs/cairo/blob/92d5f1ce477871d5e93914fc238bc9662890e023/crates/cairo-lang-sierra-to-casm/src/invocations/boxing.rs#L21)
> Fix builtin usage in Box ForwardSnapshot libfunc

- src/libfuncs/mem.rs
Fixes range check counting in every libfunc contained in `libfuncs/mem.rs`.
The following libfuncs use `build_noop()` which adds to the builtin if it is a parameter. So for example if we call `store_temp<RangeCheck>` it will add 1 to the range check builtin. However, I dont see that the same is being done on the compilers side: 
- `store_temp()`
- `finalize_locals()`
- `rename()`
> fix range check counting in `libfuncs/mem.rs`

- src/libfuncs/bounded_int.rs
We should not process builtins, as the compiler is using `build_identity`, which does not increment builtins.
-[ Sierra to casm code.](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/int/bounded.rs?plain=1#L47)
> Fix builtin counting for bounded_int_wrap_non_zero

- src/libfuncs.rs
Disables builtin processing for the following libfuncs, as the sierra to casm code doesn't increase any builtin pointer.
- [ApTracking](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs?plain=1#L20)
- [BranchAlign](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs?plain=1#L104)
- [UnconditionalJump](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/misc.rs?plain=1#L78)
> Don't process builtins for noops in libfuncs.rs

- src/libfuncs/nullable.rs
Disables builtin processing for the following libfuncs, as the sierra to casm compiler calls build_identity, which does not increase any builtin pointer.
- [ForwardSnapshot](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/nullable.rs?plain=1#L26)
- [NullableFromBox](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/nullable.rs?plain=1#L23)
> Don't process builtins for noops in nullable libfuncs

- src/libfuncs/starknet.rs
Disables builtin processing for the following libfuncs, as the sierra to casm compiler calls `build_identity`, which does not increase any builtin pointer.
- [ClassHashToFelt252](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs?plain=1#L41)
- [ContractAddressToFelt252](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs?plain=1#L41)
- [StorageAddressFromBase](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/starknet/mod.rs?plain=1#L45)
- [StorageAddressToFelt252](https://github.com/starkware-libs/cairo/blob/ …
> Don't process builtins for noops in starknet libfuncs

- src/libfuncs/circuit.rs
In the error case, we were adding `number of evaluated gates * 4`, instead of `number of evaluated gates * 7`, which is the correct value. (`MUL_MOD_BUILTIN_SIZE = 7`)
This PR also adds some documentation to how builtin counting works for the eval_circuit libfunc.
- [Sierra to casm code](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs?plain=1#L180).
> Fixes eval_circuit builtin counting.

- src/libfuncs/circuit.rs
Instead of calling `build_noop`, I created a new function `build_u96_guarantee_verify` that increases the range_check96 builtin by 1.
- [Sierra to casm code.](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/circuit.rs?plain=1#L523)
> Fixes u96_guarantee_verify builtin counting

- src/libfuncs/felt252_dict.rs
Creating a new dictionary should increment the segment arena builtin by 3. 
- [Sierra to CASM code](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/felt252_dict.rs?plain=1#L45)
The size of the arena segment builtin is 3, which means that each builtin use requires 3 cells.
> Fix new dictionary segment arena increment

- src/libfuncs.rs
The sierra to casm compiler uses build_identity, which doesn't process builtins.
- [Sierra to casm code.](https://github.com/starkware-libs/cairo/blob/dc8b4f0b2e189a3b107b15062895597588b78a46/crates/cairo-lang-sierra-to-casm/src/invocations/mod.rs?plain=1#L696)
> Fix unwrap non zero builtin processing

- src/libfuncs.rs
- src/libfuncs/int.rs
Libfunc: `build_u128s_from_felt252()`
- [Native](https://github.com/lambdaclass/cairo_native/blob/470083391c0c4a55e8860e1993389b0b029a53d1/src/libfuncs/int.rs#L818): increments range_check builtin by 1
- [Compiler](https://github.com/starkware-libs/cairo/blob/96625b57abee8aca55bdeb3ecf29f82e8cea77c3/crates/cairo-lang-sierra-to-casm/src/invocations/int/unsigned128.rs#L234): if *is_u128* is not equal to 0 range_check is incremented by 1. Else, if it is equal to 0, the range_check is incremented by 3.
**Changes**
- Use increment_builtin_counter_by_if() to add the corresponding amount to the range_check builtin according to the condition
> Fix build_u128s_from_felt252() range_check increment

- src/libfuncs/ec.rs
Libfunc: `build_state_add_mul()`
- [Native](https://github.com/lambdaclass/cairo_native/blob/470083391c0c4a55e8860e1993389b0b029a53d1/src/libfuncs/ec.rs#L239): increments ec_op builtin by 1
- [Compiler](https://github.com/starkware-libs/cairo/blob/ff2e19a3d671036e626ea89cac409c5325383584/crates/cairo-lang-sierra-to-casm/src/invocations/ec.rs#L439): increments ec_op builtin by 7
**Changes**
- The libfunc now increments the ec_op builtin by 7
Take into account that the the size of the ec_op builtin is 7, this means that each of these requires 7 cells.
> Fix build_state_add_mul() ec_op increment

- src/libfuncs/bounded_int.rs
- src/libfuncs/bytes31.rs
- src/libfuncs/circuit.rs
- src/libfuncs/felt252_dict.rs
- src/libfuncs/int.rs
- src/libfuncs/int_range.rs
- src/libfuncs/pedersen.rs
- src/libfuncs/poseidon.rs
- src/libfuncs/starknet.rs
- src/libfuncs/uint256.rs
- src/libfuncs/uint512.rs
This PR changes the version referenced by the documentation links when updating the range check builtin to meet the one used by the blockifier in version [v0.14.0-testnet](https://github.com/starkware-libs/sequencer/tree/apollo-v0.14.0-testnet) (currently being v2.12.0-dev.1)
> Change cairo's repo version used in range check doc links

- src/libfuncs/int.rs
The upper bound is exclusive, so the i128 range would be represented as `{ lower: i128::min, upper: i128::max + 1}`. 
Similarly, to check if a range is the same as the i128 range, we must check that `lower == i128::min`, and `upper - 1 == i128::max`.
> Fix is_not_i128 condition for overflowing operation libfunc

- src/libfuncs/felt252_dict.rs
- src/metadata/runtime_bindings.rs
- src/runtime.rs
This PRs fixes felt252_dict_squash libfunc, so that it updates the range check builtin correctly.
Before this PR, we use to call `cairo_native__dict_gas_refund` for calculating how much gas to refund when squashing dictionaries. Now, we actually need to do update both the gas builtin and the range check builtin. As a C compatible rust function cannot return two different values, I renamed `cairo_native__dict_gas_refund` to `cairo_native__dict_squash`, and modified the signature so that it receives a pointers to the both builtins, allowing us to modify both values.
In addition to this signature change, I properly implemented the runtime function to update the range check correctly, and added a test that was validated with the CairoVM.
The squash libfunc has a fixed range check cost of at …
> Fix felt252_dict_squash builtin counting

- .github/workflows/daily.yml
The daily workflow is currently running with an old version of the sequencer. This causes it to have differences with the builtin counting. This PR updates it to the correct one.
> Change sequencer's reference from replay to main-v0.14.0 in block's daily workflow

- src/debug.rs
Implements the `type_to_name` debug function. Useful when trying to understand a type without debug info.
> Add type_to_name debug function

- .github/workflows/starknet-blocks.yml
- scripts/cmp_state_dumps.py
This PR updates both the sequencer and the replays' ref in starknet-blocks workflow so that the point to the same ref as the daily workflow. Additionally, it change the cmp_state_dumps script to ignore the new introduced flag `cairo_native` which tells whether the entrypoint was run with cairo native or not.
> Update sequencer's and starknet replay's ref in starknet-blocks workflow and fix cmp_script

- README.md
In MacOs vscode, rust-analyzer will fail if it can't find the envar to reach llvm. We need to specify them through the setting.json. This PR adds this config to the Readme
> Add Vscode config for rust analyzer to the Readme

- src/libfuncs/circuit.rs
- src/types/circuit.rs
Instead of converting gate values from integer to struct form in the circuit_eval libfunc, they are lazily converted in the get_output libfunc. This avoids converting gate values that will never be read.
Also, adds some documentation to the circuit lowering.
This PR contains one of the optimizations included in https://github.com/lambdaclass/cairo_native/pull/1344. It seems that the other optimization (dynamic array while evaluating circuit) doesn't improve compilation, so there is no need to merge it for now.
These benchmarks were executed in a Macbook M4 Pro.
I compiled several circuit-heavy contract classes, and compared the compilation time before and this PR. The contract classes were compiled with optimization level -O2.
| Class Hash | Before | After | Improvement |
| ---------- | …
> Optimization: lazy conversion of circuit outputs to struct form

- src/bin/cairo-native-compile.rs
This PR adds support for saving total compilation time statistic in the cairo-native-compile binary.
> Save total compilation time statistic in cairo-native-compile binary

- Cargo.toml
> Move cairo-lang-sierra-generator to dev-dependencies

- src/libfuncs/circuit.rs
- src/types/circuit.rs
Reverts the optimization done to circuits in #1348 
No.
> [0.6.2] Revert circuit optimization

- Cargo.lock
- Cargo.toml
- README.md
- Reverts circuit optimization: https://github.com/lambdaclass/cairo_native/pull/1397
- Bumps Cairo dependencies: https://github.com/lambdaclass/cairo_native/pull/1398
> Prepare for 0.6.2

- src/starknet.rs
Closes #NA
This PR remove a TODO for struct U256 as we agreed it is not actually necessary. 
No.
These PRs should be merged after this one right away, in that order.
> Remove todo for struct `U256`

- src/libfuncs/felt252.rs
Closes #1214 
Closes #143
This PR fixes felt_const operations. The error was rising because we were converting the const operation incorrectly. In addition to this fix, I added the missing tests for every operation.
No.
These PRs should be merged after this one right away, in that order.
> Fix `felt_const` arithmetic operations
